version: 2

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
