version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats: all

submodules:
  include:
    - micropip/_vendored/packaging
  recursive: true

python:
  install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
