version: "2"
services:
  cors-proxy:
    image: nginx:alpine
    ports:
      - 13141:13141
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      devpi:
        condition: service_healthy
  devpi:
    image: ghcr.io/ryanking13/micropip/devpi:230502_2  # TODO: use pyodide organization
    ports:
      - 3141:3141
    environment:
      - BASE_URL=http://localhost:13141/devpi/
    healthcheck:
      # Check for a file that is only created after devpi is ready
      test: "test -f /tmp/.devpi-ready"
      interval: 2s
      timeout: 30s
      retries: 10
