name: Build devpi docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:devpi"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/devpi:${{ github.event.inputs.tag }}
